# action name
name: Tests with Jest

# when to fire
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master, modernizing-devenvs ]

jobs:
  coverage:
    runs-on: ubuntu-latest
   
    strategy:
      matrix:
        node-version: "14.x"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm test
